"""
companies to be validated  from validator API
"""

companies = [
    "abb",
    "accace",
    "ad01",
    "adm",
    "admgroup",
    "alight",
    "ascentcore",
    "autocobalcescu",
    "avantajplay",
    "bayutdubizzle",
    "beshapingthefuture",
    "bluewiresoftware",
    "boatyardx",
    "bosch",
    "breakpointit",
    "brinel",
    "chorus",
    "codezilla",
    "cognizant",
    "computacenter",
    "concentrix",
    "danfoss",
    "Db Schenker",
    "deloitte",
    "E.ON Business Services Cluj",
    "E.On Energie Romania",
    "eeusoftware",
    "encora",
    "engie",
    "erm",
    "esolution",
    "Estee Lauder Companies",
    "exiger",
    "expleo",
    "expressoft",
    "ezugi",
    "fntsoftware",
    "Freudenberg Performance Materials SRL",
    "gameloft",
    "genpact",
    "globallogic",
    "gopro",
    "grab",
    "Green Tree Marketing",
    "hennlich",
    "hirschmann automotive",
    "hungrybytes",
    "imaginelive",
    "infotreeglobalsolutions",
    "interratravel",
    "kenvue",
    "kronospan",
    "luxoft",
    "mediagalaxy",
    "morgansol",
    "movate",
    "napa",
    "nshift",
    "olinio",
    "partnerd",
    "pkf",
    "premierresearch",
    "quest global",
    "roland berger",
    "sampamind",
    "scandiweb",
    "seimaf",
    "selfpay",
    "simavi",
    "sostenia",
    "sowelo",
    "stihl",
    "swicon",
    "synopsys",
    "tec:agency",
    "tecalliance",
    "vibracoustic",
    "voxility",
    "webasto",
    "windsoft",
    "wipro",
    "wizz air",
    "yougov",
    "zenitech",
    "zonkwave",
    "Philip Morris",
    "Heimdal",
    "pluxee",
    "humancapital",
]

# companies = ["pluxee"]


sorted_companies = sorted(companies, key=lambda x: x.lower())

print(f"Number of comany to be tested:{len(companies)}")
